'\" t
.\"     Title: dmrconf
.\"    Author: Hannes Matuschek <hmatuschek@gmail.com>
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 01/21/2021
.\"    Manual: User Commands
.\"    Source: dmrconf 0.5.2
.\"  Language: English
.\"
.TH "DMRCONF" "1" "01/21/2021" "dmrconf 0\&.5\&.2" "User Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dmrconf \- Command\-line tool for programming DMR radios\&.
.SH "SYNOPSIS"
.HP \w'\fBdmrconf\fR\ 'u
\fBdmrconf\fR [\fBOPTIONS\fR] [\fBCOMMAND\fR] [file]
.SH "DESCRIPTION"
.PP
\fBdmrconf\fR
is a command\-line tool to programm DMR radios\&. That is, generating and uploading codeplugs to these radios\&. To this end,
\fBdmrconf\fR
uses a common human\-readable text format to describe the codeplug for all supported radios (see below)\&. This allows to share codeplugs between different radios\&.
.PP
Additionally,
\fBdmrconf\fR
also allows to download codeplugs from the radio and to store it in the human\-readable text format\&.
.SH "COMMANDS"
.PP
\fBdetect\fR
.RS 4
Detects a connected radio\&. This command does not take any additional options\&.
.RE
.PP
\fBread\fR
.RS 4
Reads a codeplug from the radio and stores it into the given file\&. This command may need the
\fB\-c\fR
or
\fB\-b\fR
options if the file type cannot be inferred from the filename\&.
.RE
.PP
\fBwrite\fR
.RS 4
Writes the specified codeplug to the radio\&. This command may need the
\fB\-c\fR
or
\fB\-b\fR
options if the file type cannot be inferred from the filename\&.
.RE
.PP
\fBwrite\-db\fR
.RS 4
Writes the call\-sign database to the device\&. This command may need the
\fB\-\-id\fR
option to select call\-signs if the complete database does not fit into the device\&. If specified, all callsigns closest to the specified ID are used\&.
.RE
.PP
\fBverify\fR
.RS 4
Verifies the codeplug with the connected radio or the specified radio passed with the
\fB\-\-radio\fR
option\&. This command may also need the
\fB\-c\fR
or
\fB\-b\fR
options if the file type cannot be inferred from the filename\&.
.RE
.PP
\fBencode\fR
.RS 4
Encodes a CSV codeplug as a binary one for the connected or specified radio using the
\fB\-\-radio\fR
option\&.
.RE
.PP
\fBencode\-db\fR
.RS 4
Encodes the call\-sign datavase as a binary one for the connected or specified radio using the
\fB\-\-radio\fR
option\&. This command may need the
\fB\-\-id\fR
option to select call\-signs if the complete database does not fit into the device\&. If specified, all callsigns closest to the specified ID are used\&.
.RE
.PP
\fBdecode\fR
.RS 4
Decodes a binary codeplug and stores the result in human\-readable form\&.
.RE
.PP
\fBinfo\fR
.RS 4
Prints some information about the given file\&.
.RE
.SH "OPTIONS"
.PP
\fB\-c\fR or \fB\-\-csv\fR
.RS 4
Specifies the file format for the input or output file for the
\fBverify\fR,
\fBread\fR
and
\fBwrite\fR
commands\&. This option is not needed if the filetype can be inferred from the filename\&. That is, if the file ends on
\&.conf
or
\&.csv\&.
.RE
.PP
\fB\-b\fR or \fB\-\-bin\fR
.RS 4
Specifies the file format for the input or output file for the
\fBverify\fR,
\fBread\fR
and
\fBwrite\fR
commands\&. This option is not needed if the filetype can be inferred from the filename\&. That is, if the file ends on
\&.bin
or
\&.dfu\&.
.RE
.PP
\fB\-R\fR or \fB\-\-radio=\fRNAME
.RS 4
Specifies the radio for the
\fBverify\fR,
\fBencode\fR
or
\fBdecode\fR
commands\&.
.RE
.PP
\fB\-I\fR or \fB\-\-id=\fRDMR_ID
.RS 4
Specifies the DMR ID for the
\fBwrite\-db\fR
or
\fBencode\-db\fR
commands\&.
.RE
.SH "SUPPORTED RADIOS"
.PP
The following list contains all supported radios and their names for the
\fB\-\-radio\fR
option\&.
.PP
\fBopengd77\fR
.RS 4
All radios running the Open GD77 firmeare
.RE
.PP
\fBd878uv\fR
.RS 4
Anytone AT\-D878UV
.RE
.PP
\fBmd390\fR
.RS 4
TYT MD\-390 or Retevis RT3S
.RE
.PP
\fBgd77\fR
.RS 4
Retevis GD\-77
.RE
.PP
\fBrd5r\fR
.RS 4
Baofeng/Radioddity RD\-5R
.RE
.SH "BUGS"
.PP
This programm is still under development and may contain bugs that may cause harm to the radios and may even destroy them\&. Hence you may use this software on your own risk\&. I you want to have guaranties, consider using the CPS (code\-plug programming software) supplied with your radio\&.
.SH "AUTHOR"
.PP
\fBHannes Matuschek\fR <\&hmatuschek@gmail\&.com\&>
.RS 4
Main author
.RE
